import type { NextPage } from 'next';
import Head from 'next/head';

import { Fade } from 'react-awesome-reveal';
import { Footer, HeroSection, Header, FeatureSection } from '../views/landing';

const Home: NextPage = () => {
	return (
		<div className="flex-1">
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<Fade triggerOnce>
				<HeroSection />
			</Fade>

			<FeatureSection />

			<Footer />
		</div>
	);
};

export default Home;
